version: "3.9"

services:
  mariadb:
    image: mariadb:11.4
    container_name: evtnet-mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: evtnet_db
      MARIADB_USER: evtnet_user
      MARIADB_PASSWORD: evtnet_pass
      MARIADB_ROOT_PASSWORD: root_pass
      MARIADB_AUTO_UPGRADE: "1"
      TZ: "UTC"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mariadb/init:/docker-entrypoint-initdb.d:ro   # scripts SQL al iniciar
      - ./storage/backups:/backups                      # backups accesibles por el host
    networks:
      - evtnet-net

  evtnet-back:
    build: .
    image: evtnet-back:latest
    container_name: evtnet-back
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - ./storage/perfiles:/app/storage/perfiles
      - ./storage/logs:/app/storage/logs
      - ./uploads:/app/uploads
      - /var/run/docker.sock:/var/run/docker.sock      # backend puede hacer docker exec
      - ./storage/backups:/backups                     # mismo volumen que mariadb para accesibilidad
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/evtnet_db
      SPRING_DATASOURCE_USERNAME: evtnet_user
      SPRING_DATASOURCE_PASSWORD: evtnet_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      APP_JWT_SECRET: "CLAVE_SECRETA_SUPER_SEGURA_2025_X"
      APP_JWT_EXPIRATION: "3600000"

      APP_STORAGE_PERFILES: "/app/storage/perfiles"
      APP_STORAGE_LOGS: "/app/storage/logs"

      BACKUP_CONTAINER_NAME: "evtnet-mariadb"          # para el executor
      BACKUP_BASE_PATH: "/backups"                     # donde se escriben los backups

    networks:
      - evtnet-net

volumes:
  mysql_data:

networks:
  evtnet-net:
    driver: bridge
