version: "3.9"

services:
  mariadb:
    image: mariadb:11.4
    container_name: evtnet-mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: evtnet_db
      MARIADB_USER: evtnet_user
      MARIADB_PASSWORD: evtnet_pass
      MARIADB_ROOT_PASSWORD: root_pass
      MARIADB_AUTO_UPGRADE: "1"
      TZ: "America/Argentina/Buenos_Aires"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mariadb/init:/docker-entrypoint-initdb.d:ro
    networks:
      - evtnet-net

  evtnet-back:
    build: .
    image: evtnet-back:latest
    container_name: evtnet-back
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage/perfiles:/app/storage/perfiles
      - ./storage/logs:/app/storage/logs
      - ./uploads:/app/uploads
      - ./storage/iconos:/storage/iconos
      - ./storage/documentacion:/storage/documentacion
      - ./storage/imagenesEspacio:/storage/imagenesEspacio
      - ./storage/tipoCalificacion:/storage/tipoCalificacion
      - ./storage/backups:/app/backups
    ports:
      - "8080:8080"
    environment:
      # DB (dentro de la red el host es el nombre del service: mariadb)
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/evtnet_db
      SPRING_DATASOURCE_USERNAME: evtnet_user
      SPRING_DATASOURCE_PASSWORD: evtnet_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      # JWT por ENV (sobrescribe lo del application.properties)
      APP_JWT_SECRET: "CLAVE_SECRETA_SUPER_SEGURA_2025_X"
      APP_JWT_EXPIRATION: "3600000"

      # Ruta de storage
      APP_STORAGE_PERFILES: "/app/storage/perfiles"
      APP_STORAGE_LOGS: "/app/storage/logs"

      TZ: "America/Argentina/Buenos_Aires"

    networks:
      - evtnet-net

volumes:
  mysql_data:

networks:
  evtnet-net:
    driver: bridge